name: py3createtorrent
on:
  workflow_dispatch:
    inputs:
      name:
        description: harry
        required: true
        default: Firefox Setup 95.0.1
      comment:
        description: lol
        required: true
        default: your a faggot harry
      url:
        description: URL of the file
        required: true
        default: 'https://dl.myabandonware.com/t/ZGQHELeVqwuWP4azKx8fO8j5Mptl89EZ79COYU8hItATeubcHE/Harry-Potter-and-the-Order-of-the-Phoenix_Win_EN_ISO-Version.zip'
      file_name:
        description: File name of the file in the torrent
        required: true
        default: Firefox Setup 95.0.1.exe
      piece_size:
        description: Piece Size. Use 0 for automatic calculation, or use the recommended piece size on the README.md file
        required: true
        default: 21
      maximize_disk_space:
        description: Maximize disk space. Set to true if getting out of disk space error
        default: false
        
jobs:
  create_torrent:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        if: github.event.inputs.maximize_disk_space == 'true'
        uses: easimon/maximize-build-space@v5
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          
      - name: Install py3createtorrent
        run: pipx install py3createtorrent
        
      - name: Download file
        run: aria2c -x 16 -o "${{ github.event.inputs.file_name }}" "${{ github.event.inputs.url }}"
        
      - name: Create torrent using py3createtorrent
        run: py3createtorrent -p "${{ github.event.inputs.piece_size }}" -c "${{ github.event.inputs.comment }}" -s "torrent-webseed-creator" -o "${{ github.event.inputs.name }}.torrent" --webseed "${{ github.event.inputs.url }}" "${{ github.event.inputs.file_name }}"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.name }}
          path: ${{ github.event.inputs.name }}.torrent
